apiVersion: v1
kind: ConfigMap
metadata:
  name: notifier
  namespace: default
data:
  notifier.conf: |
    {
      server: {
        bind_address: "0.0.0.0"
        bind_port: 8080
      }

      ftp: {
        username: "notifier"
        password: ${FTP_PASS}
        host: "localhost"
        port: "22"
        protocol: "sftp"
      }
    }
