apiVersion: v1
kind: Service
metadata:
  name: notifier
  namespace: default
  labels:
    k8s-app: notifier
spec:
  selector:
    k8s-app: notifier
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      nodePort: 30000
